# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3a6268049752b224802e944d578afa07f09672f1da32366a48cecbc6974ac13720405d7b4b6fdbe0a0bea2fa813a407b4939d9008a7e72831cc3d2fbca68034

test:
  secret_key_base: 96b8f35db69231abeedb31ff23b0df01621788e3b79b989b25cb79fdd2c687321fec02c8996a34fab0e27fc5728e796393eae0f453d5cbfde5b41166e5581b93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
